backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"     # Où les images sont stockées dans le repo
public_folder: "/images/uploads"   # URL publique des images

collections:
  - name: "articles"          
    label: "Actualités"       
    folder: "content/actualites"   # Dossier des articles dans le repo
    create: true                   # Autoriser la création de nouveaux fichiers
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Nom du fichier généré
    fields:
      - { name: "title", label: "Titre", widget: "string" }
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "body", label: "Contenu", widget: "markdown" }
      - { name: "image", label: "Image principale", widget: "image", required: false }